import '../styles/globals.css'
import {Box} from "@mui/material";
import Header from "../components/Header";
import React from "react";
import Head from "next/head";
import {ThemeProvider} from "@mui/styles";
import theme from "../components/theme";

function MyApp({ Component, pageProps }) {
  return (
      <Box >
          <ThemeProvider theme={theme}>

          <Head>
              <title>Weather app</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
              <meta name="viewport" content="initial-scale=1, width=device-width" />
          </Head>
          <Box sx={{position : 'relative'}}>

          <Header/>
          </Box>

   <Component {...pageProps} />
          </ThemeProvider>

      </Box> )
}

export default MyApp